Feat/add google cloud firestore support
micronaut-projects/micronaut-eclipsestore pull request #85
Opened 2024-08-17 12:52 UTC by SimonFrauenschuh

# Add Support for Azure Blob Storage

Following the code and tests of the Micronaut implementation of the azure blob-storage-client, I've implemented something similar for Firebase.

## Problem
All tests - if run individually - pass.
But if I run them via `./gradlew check`, `FirestoreStorageSpec` fails when trying to access the firestore-emulator docker-image with the following error-message:
```
Caused by: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
```

2024-08-18 01:14 UTC, anandjaisy commented
@SimonFrauenschuh Does this also support gcp cloud storage https://cloud.google.com/storage?hl=en

2024-08-18 12:09 UTC, SimonFrauenschuh commented
> @SimonFrauenschuh Does this also support gcp cloud storage https://cloud.google.com/storage?hl=en

[EclipseStore](https://docs.eclipsestore.io/manual/storage/storage-targets/index.html) has no support (yet) for google cloud storage so the short answer is no because you can't use the [Firestore](https://mvnrepository.com/artifact/com.google.cloud/google-cloud-firestore/3.25.0) client that is required by EclipseStore.

Currently, there seems to be no direct support, but you can try using the [S3Client](https://mvnrepository.com/artifact/software.amazon.awssdk/s3/2.27.7) and accessing googles [XML-Endpoint](https://cloud.google.com/storage/docs/interoperability?hl=en). According to the documentation I've read until now there might be a change that because there is a S3-compatible endpoint you can use (Micronaut) EclipseStore for AWS S3.

(Maybe [this tutorial](https://cloud.google.com/storage/docs/aws-simple-migration?hl=en) works for you? _(Note: You have to use the `S3Client`, not the `AmazonS3`)_)

2024-11-08 10:44 UTC, sdelamo requested changes
@SimonFrauenschuh Thanks for the contribution. 

The test `FirestoreStorageSpec` is failing for me. 

can you check it?

2024-11-21 19:06 UTC, SimonFrauenschuh commented
> @SimonFrauenschuh Thanks for the contribution. 
> 
> 
> 
> The test `FirestoreStorageSpec` is failing for me. 
> 
> 
> 
> can you check it?

Sorry, I have a few exams right now in university, will probably take a few days (weeks).

If the test is executed alone, it works, but I'll try to the tests.

2025-01-22 20:18 UTC, SimonFrauenschuh commented
Definitely not the best fix but I didn't manage to find another docker image that starts faster.

2026-05-01 05:34 UTC, merged